//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnit
    {
        public System.Guid UnitId { get; set; }
        public string UnitName { get; set; }
        public string MasterUnit { get; set; }
        public double ConversionFactor { get; set; }
    }
}
